export const audioBtn= '[data-testid=state-icon] > path';
export const audioTrackName= '#podcast-episode-headline';
export const playerBtn= 'body > div.MuiModal-root.MuiDrawer-root.MuiDrawer-modal.css-yqivbj-MuiModal-root-MuiDrawer-root > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-elevation16.MuiDrawer-paper.MuiDrawer-paperAnchorBottom.css-105yjo-MuiPaper-root-MuiDrawer-paper > div > div.draw-small.css-vjrmxc-upper-section > div > div.MuiBox-root.css-l6ct9h > div.MuiBox-root.css-13yz9fp > div.MuiBox-root.css-1tadesa > button.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButtonBase-root.css-vcl139-MuiButtonBase-root-MuiButton-root > span';
export const forwardplayBtn= 'body > div.MuiModal-root.MuiDrawer-root.MuiDrawer-modal.css-yqivbj-MuiModal-root-MuiDrawer-root > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-elevation16.MuiDrawer-paper.MuiDrawer-paperAnchorBottom.css-105yjo-MuiPaper-root-MuiDrawer-paper > div > div.draw-small.css-vjrmxc-upper-section > div > div.MuiBox-root.css-l6ct9h > div.MuiBox-root.css-13yz9fp > div.MuiBox-root.css-1tadesa > button:nth-child(4) > svg';
export const audioPlayerCloseBtn= 'body > div.MuiModal-root.MuiDrawer-root.MuiDrawer-modal.css-yqivbj-MuiModal-root-MuiDrawer-root > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-elevation16.MuiDrawer-paper.MuiDrawer-paperAnchorBottom.css-105yjo-MuiPaper-root-MuiDrawer-paper > div > div.draw-small.css-vjrmxc-upper-section > div > div.MuiBox-root.css-c67lzo > button.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButtonBase-root.css-3x0wdy-MuiButtonBase-root-MuiButton-root > svg > path';
export const rewindBtn= '[data-testid=fullplayer-rewind] > svg';
export const TimerValue= 'body > div.MuiModal-root.MuiDrawer-root.MuiDrawer-modal.css-yqivbj-MuiModal-root-MuiDrawer-root > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-elevation16.MuiDrawer-paper.MuiDrawer-paperAnchorBottom.css-105yjo-MuiPaper-root-MuiDrawer-paper > div > div.draw-small.css-vjrmxc-upper-section > div > div.MuiBox-root.css-l6ct9h > div.MuiBox-root.css-by529t > span > span.MuiSlider-thumbColorPrimary.MuiSlider-thumbSizeMedium.MuiSlider-thumb.css-13tm8ev-MuiSlider-thumb > input[type=range]';
export const playControl= '[data-testid=fullplayer-play] > svg > path';
export const playtimeCount= 'body > div.MuiModal-root.MuiDrawer-root.MuiDrawer-modal.css-yqivbj-MuiModal-root-MuiDrawer-root > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-elevation16.MuiDrawer-paper.MuiDrawer-paperAnchorBottom.css-105yjo-MuiPaper-root-MuiDrawer-paper > div > div.draw-small.css-vjrmxc-upper-section > div > div.MuiBox-root.css-l6ct9h > div.MuiBox-root.css-by529t > div > p:nth-child(1)';
export const volumeControl= '[data-testid=volume-icon]';
export const langSelection= '[data-testid=language-selector-label]';
export const volSlider= 'body > div.MuiModal-root.MuiDrawer-root.MuiDrawer-modal.css-yqivbj-MuiModal-root-MuiDrawer-root > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-elevation16.MuiDrawer-paper.MuiDrawer-paperAnchorBottom.css-105yjo-MuiPaper-root-MuiDrawer-paper > div > div.draw-small.css-vjrmxc-upper-section > div > div.MuiBox-root.css-l6ct9h > div.MuiBox-root.css-13yz9fp > div.MuiBox-root.css-g6aown > div > div > div';
export const volSliderInput= 'body > div.MuiModal-root.MuiDrawer-root.MuiDrawer-modal.css-yqivbj-MuiModal-root-MuiDrawer-root > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-elevation16.MuiDrawer-paper.MuiDrawer-paperAnchorBottom.css-105yjo-MuiPaper-root-MuiDrawer-paper > div > div.draw-small.css-vjrmxc-upper-section > div > div.MuiBox-root.css-l6ct9h > div.MuiBox-root.css-13yz9fp > div.MuiBox-root.css-g6aown > div > div > div > span > span.VolumeSlider-thumb.MuiSlider-thumbColorPrimary.MuiSlider-thumbSizeMedium.MuiSlider-thumb.css-13tm8ev-MuiSlider-thumb > input[type=range]';
export const multiLangOption= '#content-description > div:nth-child(3) > div.css-10lc6z4-media-query > div > div > a > span'